spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/perpus
    username: secretperpus
    password: secretpassword
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximumPoolSize: 15
      autoCommit: true
      poolName: hikariPerpus
      maxLifeTime: 1800000
      connectionTimeOut: 30000
      minimumIdle: 10
      idleTimeOut: 100
    timeBetweenEvictionRunsMillis: 18800
  jpa:
    hibernate:
      ddlAuto: validate
      useNewIdGeneratorMappings: false
      openInView: false
    showSql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: <email>
    password: <password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    mode: HTML
    cache: false

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
      enabled: true
server:
  port: 8080
  ssl:
    key-store: perpus.pfx
    key-store-password: kalabatj20
    key-store-type: PKCS12
    key-alias: sispur
    enabled: false
  error:
    whitelabel:
      enabled: false


facebook:
  client:
    clientId: <clientID>
    clientSecret: <clientSecret>
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: email public_profile
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=id,first_name,middle_name,last_name,name,email

google:
  client:
    clientId: <clientID>
    clientSecret: <ClientSecret>
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope: profile email
  resource:
    userInfoUri:  https://www.googleapis.com/oauth2/v3/userinfo

github:
  client:
    clientId: <clientId>
    clientSecret: <clientSecret>
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri:  https://api.github.com/user


security:
  oauth2:
    client:
      preEstablishedRedirectUri: http://localhost:8080/
